# Generated by Django 3.2.9 on 2022-01-15 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Onb_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='access_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='non_dev_targets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.IntegerField()),
                ('target', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='non_dev_weeks_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekid', models.IntegerField()),
                ('weektitle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='non_dev_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('task', models.TextField()),
                ('weeks_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Onb_app.non_dev_weeks_data')),
            ],
        ),
        migrations.CreateModel(
            name='accecss_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('name', models.TextField()),
                ('access_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Onb_app.access_section')),
            ],
        ),
    ]
