# Generated by Django 3.2.9 on 2022-01-15 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Onb_app', '0002_accecss_item_access_section_non_dev_content_non_dev_targets_non_dev_weeks_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='non_dev_content',
            name='weeks_data',
        ),
        migrations.DeleteModel(
            name='non_dev_targets',
        ),
        migrations.DeleteModel(
            name='non_dev_content',
        ),
        migrations.DeleteModel(
            name='non_dev_weeks_data',
        ),
    ]
