# Generated by Django 3.2.9 on 2022-01-15 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Onb_app', '0003_auto_20220115_0941'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='accecss_item',
            new_name='access_item',
        ),
    ]
