# Generated by Django 3.2.9 on 2021-11-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onb_app', '0003_auto_20211113_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstlogin',
            field=models.BooleanField(default=True),
        ),
    ]
