# Generated by Django 3.2.9 on 2021-11-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onb_app', '0004_profile_firstlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='onboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailguide', models.CharField(max_length=50)),
                ('onboardingbuddy', models.CharField(max_length=50)),
                ('newhire', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('ENGINEER', 'Engineer'), ('NEW_HIRE', 'New_Hire')], default='NEW_HIRE', max_length=15),
        ),
    ]
