# Generated by Django 3.2.9 on 2022-01-28 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Onb_app', '0004_rename_accecss_item_access_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='newhire_access_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('status', models.FloatField(default='0.0')),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Onb_app.onboarding')),
            ],
        ),
        migrations.CreateModel(
            name='newhire_access_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('name', models.TextField()),
                ('status', models.CharField(default='NOT YET REQUESTED', max_length=15)),
                ('newhire_access_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Onb_app.newhire_access_section')),
            ],
        ),
    ]
