# Generated by Django 3.2.9 on 2021-11-17 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onb_app', '0006_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='enddate',
            field=models.DateField(default=datetime.datetime.now, max_length=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='startdate',
            field=models.DateField(default=datetime.datetime.now, max_length=True),
        ),
    ]
