# Generated by Django 3.2.9 on 2021-11-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onb_app', '0007_auto_20211117_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='weeks_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekid', models.IntegerField()),
            ],
        ),
    ]
