# Generated by Django 3.2.9 on 2021-11-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onb_app', '0008_weeks_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboarding',
            name='id',
        ),
        migrations.RemoveField(
            model_name='weeks_data',
            name='id',
        ),
        migrations.AddField(
            model_name='weeks_data',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='weeks_data',
            name='weektitle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='newhire',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weeks_data',
            name='weekid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
