# Generated by Django 3.2.9 on 2021-11-20 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Onb_app', '0009_auto_20211118_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeks_data',
            name='content',
        ),
        migrations.CreateModel(
            name='week_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('weeks_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Onb_app.weeks_data')),
            ],
        ),
    ]
