# Generated by Django 3.2.9 on 2021-11-21 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Onb_app', '0010_auto_20211120_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekid', models.IntegerField()),
                ('newhire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Onb_app.onboarding')),
            ],
        ),
    ]
