# Generated by Django 3.2.9 on 2021-11-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onb_app', '0011_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='newhire',
            new_name='onboarding',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='weekid',
        ),
        migrations.AddField(
            model_name='progress',
            name='content',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='weektitle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='week_content',
        ),
        migrations.DeleteModel(
            name='weeks_data',
        ),
    ]
