# Generated by Django 3.2.9 on 2022-03-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onb_app', '0011_auto_20220317_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='enddate',
            field=models.DateField(blank=True, max_length=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='startdate',
            field=models.DateField(blank=True, max_length=True, null=True),
        ),
    ]
