# Generated by Django 3.2.9 on 2021-11-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onb_app', '0012_auto_20211122_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='weeks_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekid', models.IntegerField(null=True)),
                ('weektitle', models.CharField(max_length=200)),
                ('content', models.TextField(null=True)),
            ],
        ),
    ]
