# Generated by Django 3.2.9 on 2021-11-22 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Onb_app', '0013_weeks_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='onboarding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='Onb_app.onboarding'),
        ),
    ]
