# Generated by Django 3.2.9 on 2021-11-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onb_app', '0014_alter_progress_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
