# Generated by Django 3.2.9 on 2021-11-26 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Onb_app', '0016_progress_weekid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='onboarding',
        ),
        migrations.DeleteModel(
            name='onboarding',
        ),
        migrations.DeleteModel(
            name='progress',
        ),
    ]
