# Generated by Django 3.2.9 on 2021-11-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onb_app', '0017_auto_20211126_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='onboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newhire', models.CharField(max_length=50)),
                ('trailguide', models.CharField(max_length=50)),
                ('onboardingbuddy', models.CharField(max_length=50)),
                ('manager', models.CharField(max_length=50)),
                ('weekid', models.IntegerField(null=True)),
                ('weektitle', models.CharField(max_length=200, null=True)),
                ('content', models.IntegerField(null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
