# Generated by Django 3.2.9 on 2021-11-26 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Onb_app', '0018_onboarding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='onboarding',
        ),
        migrations.DeleteModel(
            name='weeks_data',
        ),
    ]
