# Generated by Django 3.2.9 on 2021-11-26 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Onb_app', '0020_content_newhire_content_newhire_targets_newhire_weeks_onboarding_targets_weeks_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='content',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='newhire_content',
            old_name='content',
            new_name='task',
        ),
    ]
