# Generated by Django 3.2.9 on 2021-11-27 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Onb_app', '0021_auto_20211126_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='weeks_data',
        ),
        migrations.RemoveField(
            model_name='newhire_content',
            name='newhire_weeks',
        ),
        migrations.RemoveField(
            model_name='newhire_targets',
            name='onboarding',
        ),
        migrations.RemoveField(
            model_name='newhire_weeks',
            name='onboarding',
        ),
        migrations.DeleteModel(
            name='targets',
        ),
        migrations.DeleteModel(
            name='content',
        ),
        migrations.DeleteModel(
            name='newhire_content',
        ),
        migrations.DeleteModel(
            name='newhire_targets',
        ),
        migrations.DeleteModel(
            name='newhire_weeks',
        ),
        migrations.DeleteModel(
            name='onboarding',
        ),
        migrations.DeleteModel(
            name='weeks_data',
        ),
    ]
