# Generated by Django 3.2.9 on 2021-11-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Onb_app', '0023_content_newhire_content_newhire_targets_newhire_weeks_onboarding_targets_weeks_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onboarding',
            old_name='manager',
            new_name='the_manager',
        ),
    ]
