# Generated by Django 3.2.9 on 2021-11-27 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Onb_app', '0025_auto_20211127_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='onboarding',
            fields=[
                ('newhire', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('trailguide', models.CharField(max_length=50)),
                ('onboardingbuddy', models.CharField(max_length=50)),
                ('the_manager', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='targets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.IntegerField()),
                ('target', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='weeks_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekid', models.IntegerField()),
                ('weektitle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='newhire_weeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekid', models.IntegerField()),
                ('weektitle', models.CharField(max_length=200)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Onb_app.onboarding')),
            ],
        ),
        migrations.CreateModel(
            name='newhire_targets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.IntegerField()),
                ('target', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=False)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Onb_app.onboarding')),
            ],
        ),
        migrations.CreateModel(
            name='newhire_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('task', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('newhire_weeks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Onb_app.newhire_weeks')),
            ],
        ),
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('task', models.TextField()),
                ('weeks_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Onb_app.weeks_data')),
            ],
        ),
    ]
