# Generated by Django 3.2.9 on 2021-12-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onb_app', '0028_content_newhire_content_newhire_targets_newhire_weeks_onboarding_targets_weeks_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newhire_weeks',
            name='status',
            field=models.FloatField(default='0.0'),
        ),
    ]
