# Generated by Django 3.2.9 on 2021-12-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onb_app', '0029_alter_newhire_weeks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
