# Generated by Django 3.2.9 on 2021-12-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onb_app', '0030_onboarding_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
    ]
